{
  "comments": [
    {
      "key": {
        "uuid": "369681ae_594dcf3d",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 13
      },
      "lineNbr": 0,
      "author": {
        "id": 1176763
      },
      "writtenOn": "2020-07-27T15:26:02Z",
      "side": 1,
      "message": "I fixed some selinux errors, and now it looks like good to move forward again. :)",
      "revId": "5387dac0bdba2134ee83bf789ecd517b4a6b8170",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}