{
  "comments": [
    {
      "key": {
        "uuid": "0162a11d_a1c2e0e0",
        "filename": "/COMMIT_MSG",
        "patchSetId": 2
      },
      "lineNbr": 10,
      "author": {
        "id": 1121838
      },
      "writtenOn": "2019-08-08T00:01:47Z",
      "side": 1,
      "message": "So, if in the previous run, I Ctrl+C my test (without TearDown call), the next test run may fail? If so, can we imporve SetUp() to clean up any previous mess properly before testing?",
      "range": {
        "startLine": 10,
        "startChar": 9,
        "endLine": 10,
        "endChar": 44
      },
      "revId": "6346992edcfda7a71538b92f5fa157d0565fb746",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    }
  ]
}