{
  "comments": [
    {
      "key": {
        "uuid": "10ad446a_87de742c",
        "filename": "toolbox/getevent.c",
        "patchSetId": 1
      },
      "lineNbr": 112,
      "author": {
        "id": 1003224
      },
      "writtenOn": "2016-11-16T00:45:34Z",
      "side": 1,
      "message": "i think just calling err(3) probably makes more sense here.",
      "revId": "b1ee0bfdf62a893aff5228263946c153ac1788f7",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "10ad446a_e7964835",
        "filename": "toolbox/getevent.c",
        "patchSetId": 1
      },
      "lineNbr": 112,
      "author": {
        "id": 1077838
      },
      "writtenOn": "2016-11-16T00:52:46Z",
      "side": 1,
      "message": "You mean just print an error and exit the process?",
      "parentUuid": "10ad446a_87de742c",
      "revId": "b1ee0bfdf62a893aff5228263946c153ac1788f7",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}