{
  "comments": [
    {
      "key": {
        "uuid": "dcbf42c0_349210af",
        "filename": "liblog/tests/liblog_test.cpp",
        "patchSetId": 1
      },
      "lineNbr": 2614,
      "author": {
        "id": 1032276
      },
      "writtenOn": "2016-10-12T23:00:09Z",
      "side": 1,
      "message": "Need to test that a subsequent log message opens everything up again.",
      "range": {
        "startLine": 2613,
        "startChar": 0,
        "endLine": 2614,
        "endChar": 65
      },
      "revId": "c6b96db343eacf629d664f5dac49bd0a6500b3d8",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}