{
  "comments": [
    {
      "key": {
        "uuid": "f4b5d6da_da4d7ac5",
        "filename": "adb/shell_service.cpp",
        "patchSetId": 1
      },
      "lineNbr": 171,
      "author": {
        "id": 1078119
      },
      "writtenOn": "2016-01-28T01:11:39Z",
      "side": 1,
      "message": "This error should probably be reported as well.",
      "range": {
        "startLine": 171,
        "startChar": 8,
        "endLine": 171,
        "endChar": 50
      },
      "revId": "fcfd909676fe9b077a9b8f44baaa598a41e01a17",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "f49a3677_0f7fba3d",
        "filename": "adb/shell_service.cpp",
        "patchSetId": 1
      },
      "lineNbr": 686,
      "author": {
        "id": 1078119
      },
      "writtenOn": "2016-01-28T01:11:39Z",
      "side": 1,
      "message": "ShellProtocol::Id",
      "range": {
        "startLine": 686,
        "startChar": 8,
        "endLine": 686,
        "endChar": 15
      },
      "revId": "fcfd909676fe9b077a9b8f44baaa598a41e01a17",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "941ada01_00c50c66",
        "filename": "adb/shell_service.cpp",
        "patchSetId": 1
      },
      "lineNbr": 689,
      "author": {
        "id": 1078119
      },
      "writtenOn": "2016-01-28T01:11:39Z",
      "side": 1,
      "message": "Suggest writing an exit code packet as well, or else I think the client will exit 0 even though the subprocess failed.",
      "revId": "fcfd909676fe9b077a9b8f44baaa598a41e01a17",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}